// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: shared/proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_shared_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetProductRequest) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SkuCode       string                 `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CategoryName  string                 `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_shared_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductResponse) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *GetProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetProductResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ValidateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ExpectedPrice float64                `protobuf:"fixed64,2,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductRequest) Reset() {
	*x = ValidateProductRequest{}
	mi := &file_shared_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductRequest) ProtoMessage() {}

func (x *ValidateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductRequest.ProtoReflect.Descriptor instead.
func (*ValidateProductRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ValidateProductRequest) GetExpectedPrice() float64 {
	if x != nil {
		return x.ExpectedPrice
	}
	return 0
}

type ValidateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateProductResponse) Reset() {
	*x = ValidateProductResponse{}
	mi := &file_shared_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductResponse) ProtoMessage() {}

func (x *ValidateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductResponse.ProtoReflect.Descriptor instead.
func (*ValidateProductResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateProductResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateProductResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

var File_shared_proto_product_product_proto protoreflect.FileDescriptor

const file_shared_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\"shared/proto/product/product.proto\x12\aproduct\"M\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x19\n" +
	"\bsku_code\x18\x02 \x01(\tR\askuCode\"\xab\x01\n" +
	"\x12GetProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bsku_code\x18\x03 \x01(\tR\askuCode\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\"^\n" +
	"\x16ValidateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12%\n" +
	"\x0eexpected_price\x18\x02 \x01(\x01R\rexpectedPrice\"s\n" +
	"\x17ValidateProductResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice2\xad\x01\n" +
	"\x0eProductService\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12T\n" +
	"\x0fValidateProduct\x12\x1f.product.ValidateProductRequest\x1a .product.ValidateProductResponseB.Z,github.com/yontech/ppob/shared/proto/productb\x06proto3"

var (
	file_shared_proto_product_product_proto_rawDescOnce sync.Once
	file_shared_proto_product_product_proto_rawDescData []byte
)

func file_shared_proto_product_product_proto_rawDescGZIP() []byte {
	file_shared_proto_product_product_proto_rawDescOnce.Do(func() {
		file_shared_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_product_product_proto_rawDesc), len(file_shared_proto_product_product_proto_rawDesc)))
	})
	return file_shared_proto_product_product_proto_rawDescData
}

var file_shared_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_product_product_proto_goTypes = []any{
	(*GetProductRequest)(nil),       // 0: product.GetProductRequest
	(*GetProductResponse)(nil),      // 1: product.GetProductResponse
	(*ValidateProductRequest)(nil),  // 2: product.ValidateProductRequest
	(*ValidateProductResponse)(nil), // 3: product.ValidateProductResponse
}
var file_shared_proto_product_product_proto_depIdxs = []int32{
	0, // 0: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	2, // 1: product.ProductService.ValidateProduct:input_type -> product.ValidateProductRequest
	1, // 2: product.ProductService.GetProduct:output_type -> product.GetProductResponse
	3, // 3: product.ProductService.ValidateProduct:output_type -> product.ValidateProductResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_product_product_proto_init() }
func file_shared_proto_product_product_proto_init() {
	if File_shared_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_product_product_proto_rawDesc), len(file_shared_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_product_product_proto_goTypes,
		DependencyIndexes: file_shared_proto_product_product_proto_depIdxs,
		MessageInfos:      file_shared_proto_product_product_proto_msgTypes,
	}.Build()
	File_shared_proto_product_product_proto = out.File
	file_shared_proto_product_product_proto_goTypes = nil
	file_shared_proto_product_product_proto_depIdxs = nil
}
