// Code generated by manual update to match proto.
package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_GetProduct_FullMethodName        = "/product.ProductService/GetProduct"
	ProductService_GetInquiryProduct_FullMethodName = "/product.ProductService/GetInquiryProduct"
	ProductService_ValidateProduct_FullMethodName   = "/product.ProductService/ValidateProduct"
)

type ProductServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetInquiryProduct(ctx context.Context, in *GetInquiryProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	ValidateProduct(ctx context.Context, in *ValidateProductRequest, opts ...grpc.CallOption) (*ValidateProductResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetInquiryProduct(ctx context.Context, in *GetInquiryProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetInquiryProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ValidateProduct(ctx context.Context, in *ValidateProductRequest, opts ...grpc.CallOption) (*ValidateProductResponse, error) {
	out := new(ValidateProductResponse)
	err := c.cc.Invoke(ctx, ProductService_ValidateProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type ProductServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetInquiryProduct(context.Context, *GetInquiryProductRequest) (*GetProductResponse, error)
	ValidateProduct(context.Context, *ValidateProductRequest) (*ValidateProductResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) GetInquiryProduct(context.Context, *GetInquiryProductRequest) (*GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInquiryProduct not implemented")
}
func (UnimplementedProductServiceServer) ValidateProduct(context.Context, *ValidateProductRequest) (*ValidateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateProduct not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "GetInquiryProduct",
			Handler:    _ProductService_GetInquiryProduct_Handler,
		},
		{
			MethodName: "ValidateProduct",
			Handler:    _ProductService_ValidateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/product/product.proto",
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetInquiryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInquiryProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetInquiryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetInquiryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetInquiryProduct(ctx, req.(*GetInquiryProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ValidateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ValidateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ValidateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ValidateProduct(ctx, req.(*ValidateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}
