// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: shared/proto/wallet/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      uint32                 `protobuf:"varint,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	HoldAmount    float64                `protobuf:"fixed64,4,opt,name=hold_amount,json=holdAmount,proto3" json:"hold_amount,omitempty"`
	Available     float64                `protobuf:"fixed64,5,opt,name=available,proto3" json:"available,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetWalletId() uint32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *GetBalanceResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetHoldAmount() float64 {
	if x != nil {
		return x.HoldAmount
	}
	return 0
}

func (x *GetBalanceResponse) GetAvailable() float64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PlaceHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceHoldRequest) Reset() {
	*x = PlaceHoldRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceHoldRequest) ProtoMessage() {}

func (x *PlaceHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceHoldRequest.ProtoReflect.Descriptor instead.
func (*PlaceHoldRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceHoldRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceHoldRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlaceHoldRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PlaceHoldRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *PlaceHoldRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type PlaceHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        uint32                 `protobuf:"varint,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	WalletId      uint32                 `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,5,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceHoldResponse) Reset() {
	*x = PlaceHoldResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceHoldResponse) ProtoMessage() {}

func (x *PlaceHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceHoldResponse.ProtoReflect.Descriptor instead.
func (*PlaceHoldResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceHoldResponse) GetHoldId() uint32 {
	if x != nil {
		return x.HoldId
	}
	return 0
}

func (x *PlaceHoldResponse) GetWalletId() uint32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *PlaceHoldResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlaceHoldResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PlaceHoldResponse) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *PlaceHoldResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReleaseHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,3,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHoldRequest) Reset() {
	*x = ReleaseHoldRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHoldRequest) ProtoMessage() {}

func (x *ReleaseHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHoldRequest.ProtoReflect.Descriptor instead.
func (*ReleaseHoldRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseHoldRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseHoldRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *ReleaseHoldRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

type ReleaseHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHoldResponse) Reset() {
	*x = ReleaseHoldResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHoldResponse) ProtoMessage() {}

func (x *ReleaseHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHoldResponse.ProtoReflect.Descriptor instead.
func (*ReleaseHoldResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseHoldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DebitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReleaseHold   bool                   `protobuf:"varint,5,opt,name=release_hold,json=releaseHold,proto3" json:"release_hold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitRequest) Reset() {
	*x = DebitRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitRequest) ProtoMessage() {}

func (x *DebitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitRequest.ProtoReflect.Descriptor instead.
func (*DebitRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *DebitRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DebitRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *DebitRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *DebitRequest) GetReleaseHold() bool {
	if x != nil {
		return x.ReleaseHold
	}
	return false
}

type DebitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitResponse) Reset() {
	*x = DebitResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitResponse) ProtoMessage() {}

func (x *DebitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitResponse.ProtoReflect.Descriptor instead.
func (*DebitResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *DebitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,4,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *CreditRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreditRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreditRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

type CreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditResponse) Reset() {
	*x = CreditResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditResponse) ProtoMessage() {}

func (x *CreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditResponse.ProtoReflect.Descriptor instead.
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *CreditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint32                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint32                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *TransferRequest) GetFromUserId() uint32 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *TransferRequest) GetToUserId() uint32 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_wallet_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_wallet_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_shared_proto_wallet_wallet_proto protoreflect.FileDescriptor

const file_shared_proto_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	" shared/proto/wallet/wallet.proto\x12\x06wallet\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\xbf\x01\n" +
	"\x12GetBalanceResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\rR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1f\n" +
	"\vhold_amount\x18\x04 \x01(\x01R\n" +
	"holdAmount\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x01R\tavailable\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"\xac\x01\n" +
	"\x10PlaceHoldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"\xc3\x01\n" +
	"\x11PlaceHoldResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\rR\x06holdId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\rR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x05 \x01(\tR\rreferenceType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"w\n" +
	"\x12ReleaseHoldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x03 \x01(\tR\rreferenceType\"/\n" +
	"\x13ReleaseHoldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xac\x01\n" +
	"\fDebitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\x12!\n" +
	"\frelease_hold\x18\x05 \x01(\bR\vreleaseHold\")\n" +
	"\rDebitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x01\n" +
	"\rCreditRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\x04 \x01(\tR\rreferenceType\"*\n" +
	"\x0eCreditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\x0fTransferRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\rR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\rR\btoUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\",\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8c\x03\n" +
	"\rWalletService\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12@\n" +
	"\tPlaceHold\x12\x18.wallet.PlaceHoldRequest\x1a\x19.wallet.PlaceHoldResponse\x12F\n" +
	"\vReleaseHold\x12\x1a.wallet.ReleaseHoldRequest\x1a\x1b.wallet.ReleaseHoldResponse\x124\n" +
	"\x05Debit\x12\x14.wallet.DebitRequest\x1a\x15.wallet.DebitResponse\x127\n" +
	"\x06Credit\x12\x15.wallet.CreditRequest\x1a\x16.wallet.CreditResponse\x12=\n" +
	"\bTransfer\x12\x17.wallet.TransferRequest\x1a\x18.wallet.TransferResponseB-Z+github.com/yontech/ppob/shared/proto/walletb\x06proto3"

var (
	file_shared_proto_wallet_wallet_proto_rawDescOnce sync.Once
	file_shared_proto_wallet_wallet_proto_rawDescData []byte
)

func file_shared_proto_wallet_wallet_proto_rawDescGZIP() []byte {
	file_shared_proto_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_shared_proto_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_wallet_wallet_proto_rawDesc), len(file_shared_proto_wallet_wallet_proto_rawDesc)))
	})
	return file_shared_proto_wallet_wallet_proto_rawDescData
}

var file_shared_proto_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shared_proto_wallet_wallet_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),   // 0: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil),  // 1: wallet.GetBalanceResponse
	(*PlaceHoldRequest)(nil),    // 2: wallet.PlaceHoldRequest
	(*PlaceHoldResponse)(nil),   // 3: wallet.PlaceHoldResponse
	(*ReleaseHoldRequest)(nil),  // 4: wallet.ReleaseHoldRequest
	(*ReleaseHoldResponse)(nil), // 5: wallet.ReleaseHoldResponse
	(*DebitRequest)(nil),        // 6: wallet.DebitRequest
	(*DebitResponse)(nil),       // 7: wallet.DebitResponse
	(*CreditRequest)(nil),       // 8: wallet.CreditRequest
	(*CreditResponse)(nil),      // 9: wallet.CreditResponse
	(*TransferRequest)(nil),     // 10: wallet.TransferRequest
	(*TransferResponse)(nil),    // 11: wallet.TransferResponse
}
var file_shared_proto_wallet_wallet_proto_depIdxs = []int32{
	0,  // 0: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	2,  // 1: wallet.WalletService.PlaceHold:input_type -> wallet.PlaceHoldRequest
	4,  // 2: wallet.WalletService.ReleaseHold:input_type -> wallet.ReleaseHoldRequest
	6,  // 3: wallet.WalletService.Debit:input_type -> wallet.DebitRequest
	8,  // 4: wallet.WalletService.Credit:input_type -> wallet.CreditRequest
	10, // 5: wallet.WalletService.Transfer:input_type -> wallet.TransferRequest
	1,  // 6: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	3,  // 7: wallet.WalletService.PlaceHold:output_type -> wallet.PlaceHoldResponse
	5,  // 8: wallet.WalletService.ReleaseHold:output_type -> wallet.ReleaseHoldResponse
	7,  // 9: wallet.WalletService.Debit:output_type -> wallet.DebitResponse
	9,  // 10: wallet.WalletService.Credit:output_type -> wallet.CreditResponse
	11, // 11: wallet.WalletService.Transfer:output_type -> wallet.TransferResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_wallet_wallet_proto_init() }
func file_shared_proto_wallet_wallet_proto_init() {
	if File_shared_proto_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_wallet_wallet_proto_rawDesc), len(file_shared_proto_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_shared_proto_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_shared_proto_wallet_wallet_proto_msgTypes,
	}.Build()
	File_shared_proto_wallet_wallet_proto = out.File
	file_shared_proto_wallet_wallet_proto_goTypes = nil
	file_shared_proto_wallet_wallet_proto_depIdxs = nil
}
