services:
    auth-service:
        build:
            context: ..
            dockerfile: auth-service/Dockerfile
        container_name: ppob-auth-service
        ports:
            - "8081:8080"
        environment:
            - SERVER_PORT=8080
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=${POSTGRES_PASSWORD:-ppob_secure_password_2024}
            - DB_NAME=ppob
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - GIN_MODE=debug
        # depends_on:
        #     postgres:
        #         condition: service_healthy
        #     redis:
        #         condition: service_healthy
        networks:
            - deployment_deployment_deployment_ppob-internal
        restart: unless-stopped

networks:
    deployment_deployment_deployment_ppob-internal:
        external: true
