import 'package:firebase_core/firebase_core.dart';

/// Firebase configuration for the current platform.
/// This file is generated by the Firebase CLI and should not be modified manually.
/// For now, we provide a placeholder. Run `flutterfire configure` to generate the actual file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'API_KEY',
      appId: 'APP_ID',
      messagingSenderId: 'SENDER_ID',
      projectId: 'PROJECT_ID',
      storageBucket: 'STORAGE_BUCKET',
      authDomain: 'AUTH_DOMAIN',
      databaseURL: 'DATABASE_URL',
    );
  }
}