import 'package:firebase_core/firebase_core.dart';

/// Firebase configuration for the current platform.
/// This file is generated by the Firebase CLI and should not be modified manually.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyDag5QHsyAj0T05zfhCg9-htmqnXon_GlU',
      appId: '1:893046057372:android:f65b36d45b953d83ce4059',
      messagingSenderId: '893046057372',
      projectId: 'ppob-uat',
      storageBucket: 'ppob-uat.firebasestorage.app',
      authDomain: 'ppob-uat.firebaseapp.com',
    );
  }
}