# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
# Allow local socket connections
local   all             all                                     scram-sha-256

# Allow replication connections from localhost
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256

# Allow remote connections from LAN
host    all             all             0.0.0.0/0        scram-sha-256
