// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: shared/proto/integration/integration.proto

package integration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InquiryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductCode    string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	RefId          string                 `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InquiryRequest) Reset() {
	*x = InquiryRequest{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquiryRequest) ProtoMessage() {}

func (x *InquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquiryRequest.ProtoReflect.Descriptor instead.
func (*InquiryRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{0}
}

func (x *InquiryRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *InquiryRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *InquiryRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type InquiryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *InquiryData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InquiryResponse) Reset() {
	*x = InquiryResponse{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquiryResponse) ProtoMessage() {}

func (x *InquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquiryResponse.ProtoReflect.Descriptor instead.
func (*InquiryResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{1}
}

func (x *InquiryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InquiryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InquiryResponse) GetData() *InquiryData {
	if x != nil {
		return x.Data
	}
	return nil
}

type InquiryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	BillAmount    float64                `protobuf:"fixed64,3,opt,name=bill_amount,json=billAmount,proto3" json:"bill_amount,omitempty"`
	AdminFee      float64                `protobuf:"fixed64,4,opt,name=admin_fee,json=adminFee,proto3" json:"admin_fee,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InquiryData) Reset() {
	*x = InquiryData{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquiryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquiryData) ProtoMessage() {}

func (x *InquiryData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquiryData.ProtoReflect.Descriptor instead.
func (*InquiryData) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{2}
}

func (x *InquiryData) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *InquiryData) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *InquiryData) GetBillAmount() float64 {
	if x != nil {
		return x.BillAmount
	}
	return 0
}

func (x *InquiryData) GetAdminFee() float64 {
	if x != nil {
		return x.AdminFee
	}
	return 0
}

func (x *InquiryData) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InquiryData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InquiryData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TopUpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductCode    string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	RefId          string                 `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopUpRequest) Reset() {
	*x = TopUpRequest{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpRequest) ProtoMessage() {}

func (x *TopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpRequest.ProtoReflect.Descriptor instead.
func (*TopUpRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{3}
}

func (x *TopUpRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *TopUpRequest) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *TopUpRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type TopUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TopUpData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpResponse) Reset() {
	*x = TopUpResponse{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpResponse) ProtoMessage() {}

func (x *TopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpResponse.ProtoReflect.Descriptor instead.
func (*TopUpResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{4}
}

func (x *TopUpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TopUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopUpResponse) GetData() *TopUpData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TopUpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	TrxId         string                 `protobuf:"bytes,2,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ScCode        string                 `protobuf:"bytes,4,opt,name=sc_code,json=scCode,proto3" json:"sc_code,omitempty"`
	ScMessage     string                 `protobuf:"bytes,5,opt,name=sc_message,json=scMessage,proto3" json:"sc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpData) Reset() {
	*x = TopUpData{}
	mi := &file_shared_proto_integration_integration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpData) ProtoMessage() {}

func (x *TopUpData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_integration_integration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpData.ProtoReflect.Descriptor instead.
func (*TopUpData) Descriptor() ([]byte, []int) {
	return file_shared_proto_integration_integration_proto_rawDescGZIP(), []int{5}
}

func (x *TopUpData) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *TopUpData) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *TopUpData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TopUpData) GetScCode() string {
	if x != nil {
		return x.ScCode
	}
	return ""
}

func (x *TopUpData) GetScMessage() string {
	if x != nil {
		return x.ScMessage
	}
	return ""
}

var File_shared_proto_integration_integration_proto protoreflect.FileDescriptor

const file_shared_proto_integration_integration_proto_rawDesc = "" +
	"\n" +
	"*shared/proto/integration/integration.proto\x12\vintegration\"s\n" +
	"\x0eInquiryRequest\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12'\n" +
	"\x0fcustomer_number\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\tR\x05refId\"s\n" +
	"\x0fInquiryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.integration.InquiryDataR\x04data\"\xdc\x01\n" +
	"\vInquiryData\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12\x1f\n" +
	"\vbill_amount\x18\x03 \x01(\x01R\n" +
	"billAmount\x12\x1b\n" +
	"\tadmin_fee\x18\x04 \x01(\x01R\badminFee\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"q\n" +
	"\fTopUpRequest\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12'\n" +
	"\x0fcustomer_number\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\tR\x05refId\"o\n" +
	"\rTopUpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.integration.TopUpDataR\x04data\"\x89\x01\n" +
	"\tTopUpData\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12\x15\n" +
	"\x06trx_id\x18\x02 \x01(\tR\x05trxId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\asc_code\x18\x04 \x01(\tR\x06scCode\x12\x1d\n" +
	"\n" +
	"sc_message\x18\x05 \x01(\tR\tscMessage2\x9a\x01\n" +
	"\x12IntegrationService\x12>\n" +
	"\x05TopUp\x12\x19.integration.TopUpRequest\x1a\x1a.integration.TopUpResponse\x12D\n" +
	"\aInquiry\x12\x1b.integration.InquiryRequest\x1a\x1c.integration.InquiryResponseB2Z0github.com/yontech/ppob/shared/proto/integrationb\x06proto3"

var (
	file_shared_proto_integration_integration_proto_rawDescOnce sync.Once
	file_shared_proto_integration_integration_proto_rawDescData []byte
)

func file_shared_proto_integration_integration_proto_rawDescGZIP() []byte {
	file_shared_proto_integration_integration_proto_rawDescOnce.Do(func() {
		file_shared_proto_integration_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_integration_integration_proto_rawDesc), len(file_shared_proto_integration_integration_proto_rawDesc)))
	})
	return file_shared_proto_integration_integration_proto_rawDescData
}

var file_shared_proto_integration_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_proto_integration_integration_proto_goTypes = []any{
	(*InquiryRequest)(nil),  // 0: integration.InquiryRequest
	(*InquiryResponse)(nil), // 1: integration.InquiryResponse
	(*InquiryData)(nil),     // 2: integration.InquiryData
	(*TopUpRequest)(nil),    // 3: integration.TopUpRequest
	(*TopUpResponse)(nil),   // 4: integration.TopUpResponse
	(*TopUpData)(nil),       // 5: integration.TopUpData
}
var file_shared_proto_integration_integration_proto_depIdxs = []int32{
	2, // 0: integration.InquiryResponse.data:type_name -> integration.InquiryData
	5, // 1: integration.TopUpResponse.data:type_name -> integration.TopUpData
	3, // 2: integration.IntegrationService.TopUp:input_type -> integration.TopUpRequest
	0, // 3: integration.IntegrationService.Inquiry:input_type -> integration.InquiryRequest
	4, // 4: integration.IntegrationService.TopUp:output_type -> integration.TopUpResponse
	1, // 5: integration.IntegrationService.Inquiry:output_type -> integration.InquiryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_integration_integration_proto_init() }
func file_shared_proto_integration_integration_proto_init() {
	if File_shared_proto_integration_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_integration_integration_proto_rawDesc), len(file_shared_proto_integration_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_integration_integration_proto_goTypes,
		DependencyIndexes: file_shared_proto_integration_integration_proto_depIdxs,
		MessageInfos:      file_shared_proto_integration_integration_proto_msgTypes,
	}.Build()
	File_shared_proto_integration_integration_proto = out.File
	file_shared_proto_integration_integration_proto_goTypes = nil
	file_shared_proto_integration_integration_proto_depIdxs = nil
}
