[versions]

# =========================
# BUILD
# =========================
agp = "8.7.3"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"

# =========================
# ANDROIDX CORE
# =========================
coreKtx = "1.15.0"

# =========================
# TEST
# =========================
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

# =========================
# LIFECYCLE
# =========================
lifecycleRuntimeKtx = "2.8.7"
lifecycleViewmodelCompose = "2.8.7"

# =========================
# COMPOSE
# =========================
activityCompose = "1.10.1"
composeBom = "2025.05.01"

# =========================
# NAVIGATION
# =========================
navigationCompose = "2.8.9"

# =========================
# HILT
# =========================
hilt = "2.56.2"
androidxHilt = "1.2.0"

# =========================
# NETWORK
# =========================
retrofit = "2.11.0"
okhttp = "4.12.0"
moshi = "1.15.2"

# =========================
# ROOM
# =========================
room = "2.7.1"

# =========================
# WORK MANAGER
# =========================
work = "2.10.1"

# =========================
# DATASTORE
# =========================
datastore = "1.1.4"

# =========================
# IMAGE
# =========================
coil = "2.7.0"

# =========================
# SECURITY
# =========================
biometric = "1.1.0"

# =========================
# FIREBASE
# =========================
firebaseBom = "33.9.0"
googleServices = "4.4.2"
crashlyticsPlugin = "3.0.2"

# =========================
# LOGGER
# =========================
timber = "5.0.1"

# =========================
# DEBUGGING
# =========================
chucker = "4.1.0"



[libraries]

# =========================================================
# CORE
# =========================================================
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# =========================================================
# TEST
# =========================================================
junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# =========================================================
# LIFECYCLE
# =========================================================
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

# =========================================================
# ACTIVITY
# =========================================================
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# =========================================================
# COMPOSE BOM
# =========================================================
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# =========================================================
# COMPOSE UI
# =========================================================
androidx-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# =========================================================
# MATERIAL
# =========================================================
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# =========================================================
# NAVIGATION
# =========================================================
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# =========================================================
# HILT
# =========================================================
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }

hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }

androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHilt" }

androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }

# =========================================================
# RETROFIT
# =========================================================
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }

retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

# =========================================================
# OKHTTP
# =========================================================
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# =========================================================
# MOSHI
# =========================================================
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }

moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

# =========================================================
# ROOM
# =========================================================
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# =========================================================
# WORK MANAGER
# =========================================================
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# =========================================================
# DATASTORE
# =========================================================
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# =========================================================
# COIL
# =========================================================
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# =========================================================
# BIOMETRIC
# =========================================================
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }

# =========================================================
# FIREBASE
# =========================================================
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }

firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }

firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

# =========================================================
# LOGGER
# =========================================================
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# =========================================================
# CHUCKER
# =========================================================
chucker-debug = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }

chucker-release = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }



[plugins]

# =========================================================
# ANDROID
# =========================================================
android-application = { id = "com.android.application", version.ref = "agp" }

# =========================================================
# KOTLIN
# =========================================================
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# =========================================================
# HILT
# =========================================================
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# =========================================================
# KSP
# =========================================================
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# =========================================================
# FIREBASE
# =========================================================
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
